# run the testsuite on travis-ci.com
---
language: C
dist: bionic
sudo: required

install:
  - sudo apt-get install build-essential debhelper/bionic-backports fakeroot iputils-ping

script:
  - dpkg-buildpackage -us -uc -rfakeroot
  - for deb in ../*.deb; do echo "$deb:"; dpkg-deb --info $deb; dpkg-deb --contents $deb; done
  - sudo dpkg -i ../*.deb
  - make check

arch:
  - amd64
  - ppc64le
